---
abstract: 'Report on prerequisite versions during automated testing'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Capture::Tiny: 0
  Cwd: 0
  Dist::Zilla::Tester: 0
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  File::Temp: 0
  File::pushd: 0
  IO::Handle: 0
  IPC::Open3: 0
  List::Util: 0
  Path::Class: 0
  Test::Harness: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-ReportPrereqs
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dist::Zilla::Plugin::Test::ReportPrereqs:
    file: lib/Dist/Zilla/Plugin/Test/ReportPrereqs.pm
    version: 0.008
requires:
  Dist::Zilla: 4
  Dist::Zilla::Plugin::InlineFiles: 0
  Dist::Zilla::Role::AfterBuild: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  Moose: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/Dist-Zilla-Plugin-Test-ReportPrereqs/issues
  homepage: https://github.com/dagolden/Dist-Zilla-Plugin-Test-ReportPrereqs
  repository: https://github.com/dagolden/Dist-Zilla-Plugin-Test-ReportPrereqs.git
version: 0.008
x_authority: cpan:DAGOLDEN
x_contributors:
  - 'Karen Etheridge <ether@cpan.org>'
  - 'Randy Stauner <randy@magnificent-tears.com>'
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
