---
abstract: 'Report on prerequisite versions during automated testing'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Capture::Tiny: 0
  Dist::Zilla::Tester: 0
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Temp: 0
  File::pushd: 0
  List::Util: 0
  Path::Class: 0
  Test::Harness: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-ReportPrereqs
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dist::Zilla::Plugin::Test::ReportPrereqs:
    file: lib/Dist/Zilla/Plugin/Test/ReportPrereqs.pm
    version: 0.005
requires:
  Dist::Zilla: 4
  Dist::Zilla::Plugin::InlineFiles: 0
  Dist::Zilla::Role::AfterBuild: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  Moose: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-Test-ReportPrereqs
  homepage: https://metacpan.org/release/Dist-Zilla-Plugin-Test-ReportPrereqs
  repository: git://github.com/dagolden/dist-zilla-plugin-test-reportprereqs.git
version: 0.005
